#pragma once

#include <chrono>
#include <cstdint>
#include <string>
#include <string_view>

#include "eventbook/common/result.hpp"

namespace eventbook {

/// Resolution of every timestamp in the project.
///
/// Microseconds, deliberately, and not nanoseconds. The exchange sends
/// milliseconds (`ts_ms`), so microseconds already preserve every digit the
/// venue actually produces. Nanoseconds would advertise measurement precision
/// this system does not have and must not claim (AGENTS.md: "Do not claim the
/// project is low latency merely because it is written in C++"). An int64 count
/// of microseconds spans roughly +/- 292,000 years, so overflow is not a
/// consideration anywhere in this codebase.
using TimeResolution = std::chrono::microseconds;

/// A point on the wall clock, at the project's resolution.
///
/// Wall clock (system_clock) rather than steady_clock because these values get
/// written to the journal and correlated across processes and runs, which a
/// monotonic clock cannot support -- its epoch is arbitrary and differs per
/// boot. The tradeoff is that wall clocks jump under NTP correction, so any
/// future code measuring an *interval* (reconnect backoff, rate-limit windows,
/// benchmark timing) must use steady_clock instead. Recording uses this type;
/// measuring does not.
using WallTime = std::chrono::sys_time<TimeResolution>;

/// A timestamp generated by Kalshi's clock, as carried in `ts_ms` or in an
/// RFC 3339 field such as `close_time`.
struct ExchangeTimestamp {
    WallTime value{};

    [[nodiscard]] friend constexpr auto operator<=>(const ExchangeTimestamp&,
                                                    const ExchangeTimestamp&) = default;
};

/// A timestamp generated by this machine's clock, recording when a message was
/// received. Never sent by the venue; always produced locally.
struct LocalTimestamp {
    WallTime value{};

    [[nodiscard]] friend constexpr auto operator<=>(const LocalTimestamp&,
                                                    const LocalTimestamp&) = default;
};

/// Elapsed time between two readings of the same clock. Safe and meaningful.
[[nodiscard]] constexpr TimeResolution operator-(ExchangeTimestamp left, ExchangeTimestamp right) {
    return left.value - right.value;
}

[[nodiscard]] constexpr TimeResolution operator-(LocalTimestamp left, LocalTimestamp right) {
    return left.value - right.value;
}

/// The difference between our receive time and the venue's stated send time.
///
/// There is deliberately no `operator-(LocalTimestamp, ExchangeTimestamp)`. This
/// quantity has to be spelled out by name, because it is routinely mistaken for
/// something it is not.
///
/// It is NOT one-way network latency. It is the sum of one-way delay, the offset
/// between Kalshi's clock and this machine's clock, and the relative drift of the
/// two -- and those three are not separable from a single endpoint. The offset
/// alone can exceed the delay, and can be negative, which is why this function
/// can legitimately return a negative duration.
///
/// Report it as an observed timestamp difference, never as latency (AGENTS.md,
/// "Data-quality requirements"). It is useful for detecting clock problems and
/// gross feed stalls; it is not evidence of transport speed.
[[nodiscard]] constexpr TimeResolution observed_timestamp_difference(LocalTimestamp local,
                                                                     ExchangeTimestamp exchange) {
    return local.value - exchange.value;
}

/// Read this machine's wall clock.
///
/// Free function rather than an injected clock, for now. That is fine while the
/// only caller is live collection, but replay must never read the system clock:
/// a deterministic replay has to take its time from the journal. When M3 adds
/// the replay engine, this becomes an injectable dependency so the two paths
/// cannot share a hidden global.
[[nodiscard]] LocalTimestamp local_now();

/// Build an ExchangeTimestamp from the `ts_ms` field of a WebSocket message.
///
/// Prefer `ts_ms` over `ts`: the seconds-resolution `ts` is documented as
/// deprecated, and one-second resolution is useless for anything we measure.
[[nodiscard]] constexpr ExchangeTimestamp exchange_time_from_epoch_millis(std::int64_t millis) {
    return ExchangeTimestamp{WallTime{std::chrono::milliseconds{millis}}};
}

[[nodiscard]] constexpr ExchangeTimestamp exchange_time_from_epoch_micros(std::int64_t micros) {
    return ExchangeTimestamp{WallTime{TimeResolution{micros}}};
}

[[nodiscard]] constexpr LocalTimestamp local_time_from_epoch_micros(std::int64_t micros) {
    return LocalTimestamp{WallTime{TimeResolution{micros}}};
}

/// Journal representation: a plain integer count of microseconds since the Unix
/// epoch, for both clocks. Integers keep the journal schema stable across
/// standard-library versions and independent of any text time format.
[[nodiscard]] constexpr std::int64_t epoch_micros(ExchangeTimestamp timestamp) {
    return timestamp.value.time_since_epoch().count();
}

[[nodiscard]] constexpr std::int64_t epoch_micros(LocalTimestamp timestamp) {
    return timestamp.value.time_since_epoch().count();
}

/// Why an RFC 3339 timestamp string could not be parsed.
enum class TimestampParseError {
    Empty,
    MalformedFormat,  ///< wrong shape: missing separator, wrong digit count, trailing junk
    InvalidDate,      ///< syntactically fine, calendrically impossible: "2026-02-30"
    InvalidTime,      ///< hour > 23, minute > 59, or a leap second ("23:59:60")
    InvalidOffset,    ///< UTC offset outside +/-23:59
};

[[nodiscard]] std::string_view to_string(TimestampParseError error);

/// Parse an RFC 3339 date-time, as used by the REST market fields.
///
/// Accepts `YYYY-MM-DDTHH:MM:SS[.fraction](Z|z|+HH:MM|-HH:MM)`, with either case
/// for the date/time separator. Numeric offsets are honoured and normalized to
/// UTC; the result is always a UTC instant.
///
/// Hand-written rather than using std::chrono::from_stream, and not by
/// preference. libc++ reports __cpp_lib_chrono == 201611, meaning the C++20
/// chrono parsing facilities are absent on macOS while present in libstdc++ on
/// the Linux CI runners -- the standard route would build on one and not the
/// other. Only the *lexing* is hand-rolled here; the proleptic Gregorian
/// calendar arithmetic is delegated to std::chrono::year_month_day and
/// sys_days, which both implementations do provide, because reimplementing
/// days-from-civil by hand is a classic source of off-by-one bugs.
///
/// Fractional seconds finer than a microsecond are TRUNCATED, not rejected.
/// This is a deliberate departure from parse_scaled_decimal, which refuses to
/// round: Kalshi's Go backend can emit up to nine fractional digits via
/// time.RFC3339Nano, and sub-microsecond precision is below the venue's own
/// clock accuracy and carries no economic meaning. A sub-cent price is money;
/// a sub-microsecond timestamp is noise.
[[nodiscard]] Result<ExchangeTimestamp, TimestampParseError> parse_rfc3339(std::string_view text);

/// Render as RFC 3339 UTC with exactly six fractional digits.
///
/// Always emits the full microsecond field, for the same reason
/// format_scaled_decimal always emits its full scale: one canonical form makes
/// output comparable and diffable.
[[nodiscard]] std::string format_rfc3339(ExchangeTimestamp timestamp);

}  // namespace eventbook
